name: lab2_kc_house
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  csv: ^6.0.0
  date_format: ^2.0.9
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_echarts: ^2.5.0
  flutter_gl: ^0.0.21
  http: ^0.13.6
  intl: ^0.20.2
  sample_statistics: ^0.2.2
  syncfusion_flutter_charts: ^31.2.2
  three_dart: ^0.0.16
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.23.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/kc_house_data.csv
    - assets/world_population.csv
    # - assets/creditcard.csv
    - assets/heart_attack_prediction_dataset.csv
    - assets/marketing_campaign.csv
    - assets/diabetes_data_upload.csv
    - assets/test.csv
